version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      maven: 3.6
    commands:
      - echo "Maven 和 Java 已经预装"
  pre_build:
    commands:
      - echo "Pre-build 阶段..."
  build:
    commands:
      - echo "构建项目..."
      - mvn clean package
  post_build:
    commands:
      - echo "构建完成，准备打包部署..."
      - mkdir -p deployment
      - ls -l target/
      - cp target/BabyFast-1.0-SNAPSHOT.jar deployment/
      - ls -l deployment/
      - cd deployment
      - echo "列出所以jar包..."
      - jar tf BabyFast-1.0-SNAPSHOT.jar
#      - zip function.zip BabyFast-1.0-SNAPSHOT.jar
      - echo "打包完成，开始更新 Lambda 函数代码..."
      - aws s3 cp BabyFast-1.0-SNAPSHOT.jar s3://word-output-bucket-yyf/new_code_zip/function.jar
      - echo "上传完成，开始更新 Lambda 函数代码..."
      - aws lambda update-function-code --function-name wordTemplateFunction --s3-bucket word-output-bucket-yyf --s3-key new_code_zip/function.jar
      - echo "Lambda 函数代码已更新"

artifacts:
  files:
    - deployment/function.zip
  discard-paths: yes
