version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build阶段...
  build:
    commands:
      - echo 构建项目...
      - mvn clean package
  post_build:
    commands:
      - echo 构建完成，准备打包部署...
      - mkdir -p deployment
      - cp target/lambda-deployment.jar deployment/
      - cd deployment
      - zip function.zip lambda-deployment.jar
artifacts:
  files:
    - deployment/function.zip
  discard-paths: yes
