version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      maven: 3.6
    commands:
      - echo "Maven 和 Java 已经预装"
  pre_build:
    commands:
      - echo "Pre-build 阶段..."
  build:
    commands:
      - echo "构建项目..."
      - mvn clean package
  post_build:
    commands:
      - echo "构建完成，准备打包部署..."
      - mkdir -p deployment
      - cp target/lambda-deployment.jar deployment/
      - cd deployment
      - zip function.zip lambda-deployment.jar
      - echo "打包完成，开始更新 Lambda 函数代码..."
      - aws lambda update-function-code --function-name LogToEmailHandler --zip-file fileb://function.zip
      - echo "Lambda 函数代码已更新"

artifacts:
  files:
    - deployment/function.zip
  discard-paths: yes
